apiVersion: v1
description: Common Helm chart for Kubernetes
name: nxs-helm-chart
version: 1.0.1
maintainers:
- name: Roman Andreev
  email: r.andreev@nixys.ru
- name: Anton Zhideev
  email: a.zhideev@nixys.ru