{{- range .Values.configmaps -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helpers.app.fullname" (dict "name" .name "context" $) }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{- include "helpers.app.labels" $ | nindent 4 }}
    {{- if .labels }}
    {{- include "helpers.tplvalues.render" (dict "value" .labels "context" $) | nindent 4 }}
    {{- end }}
    {{- if $.Values.global.labels }}
    {{- include "helpers.tplvalues.render" (dict "value" $.Values.global.labels "context" $) | nindent 4 }}
    {{- end }}
data:
  {{- include "helpers.tplvalues.render" ( dict "value" .data "context" $ ) | nindent 2 }}
{{- end -}}

{{- if $.Files.Glob ("extra-files/config/**") -}}
{{- range $subPath := splitList "$" (include "helpers.configFiles.subPaths" $)}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helpers.app.fullname" (dict "name" ($subPath | replace "_" "-") "context" $) }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{- include "helpers.app.labels" $ | nindent 4 }}
    {{- if $.Values.global.labels }}
    {{- include "helpers.tplvalues.render" (dict "value" $.Values.global.labels "context" $) | nindent 4 }}
    {{- end }}
data:
{{- if eq $subPath "extra-files" }}
{{ ($.Files.Glob  "extra-files/config/*").AsConfig | indent 2 }}
{{- else }}
{{ ($.Files.Glob (printf "extra-files/config/%s/**" $subPath)).AsConfig | indent 2 }}
{{- end -}}
{{- end -}}
{{- end -}}
