{{- $j := list -}}
{{- if .Values.jobs -}}
{{- if kindIs "string" .Values.jobs -}}
{{- $j = fromYaml (printf "jobs:\n%s" .Values.jobs) -}}
{{- else if kindIs "slice" .Values.jobs -}}
{{- $j = .Values.jobs -}}
{{- end -}}
{{- $general := $.Values.jobsGeneral -}}
{{- range $i, $job := $j }}
{{- $jobName := include "helpers.app.fullname" (dict "name" .name "context" $) }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $jobName }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{- include "helpers.app.labels" $ | nindent 4 }}
    {{- with .labels }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
  annotations:
    {{- include "helpers.app.generalAnnotations" $ | indent 4 }}
    {{- with .annotations }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
spec:
  {{- if .parallelism }}
  parallelism: {{ .parallelism }}
  {{- else if $general.parallelism }}
  parallelism: {{ $general.parallelism }}
  {{- end }}
  {{- if .completions }}
  completions: {{ .completions }}
  {{- else if $general.completions }}
  completions: {{ $general.completions }}
  {{- end }}
  {{- if .activeDeadlineSeconds }}
  activeDeadlineSeconds: {{ .activeDeadlineSeconds }}
  {{- else if $general.activeDeadlineSeconds }}
  activeDeadlineSeconds: {{ $general.activeDeadlineSeconds }}
  {{- end }}
  {{- if .backoffLimit }}
  backoffLimit: {{ .backoffLimit }}
  {{- else if $general.backoffLimit }}
  backoffLimit: {{ $general.backoffLimit }}
  {{- end }}
  {{- if .ttlSecondsAfterFinished }}
  ttlSecondsAfterFinished: {{ .ttlSecondsAfterFinished }}
  {{- else if $general.ttlSecondsAfterFinished }}
  ttlSecondsAfterFinished: {{ $general.ttlSecondsAfterFinished }}
  {{- end }}
  template:
    metadata:
      labels:
        {{- with $.Values.generic.podLabels }}{{- include "helpers.tplvalues.render" ( dict "value" . "context" $ ) | nindent 8 }}{{- end }}
        {{- with .podLabels }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 8 }}{{- end }}
      annotations:
        {{- with $.Values.generic.podAnnotations }}{{- include "helpers.tplvalues.render" ( dict "value" . "context" $ ) | nindent 8 }}{{- end }}
        {{- with .podAnnotations }}{{- include "helpers.tplvalues.render" ( dict "value" . "context" $) | nindent 8 }}{{- end }}
    spec:
      {{- if .serviceAccountName }}
      serviceAccountName: {{ .serviceAccountName }}
      {{- else if $.Values.generic.serviceAccountName }}
      serviceAccountName: {{ $.Values.generic.serviceAccountName }}
      {{- end }}
      {{- if .hostAliases }}
      hostAliases: {{- include "helpers.tplvalues.render" (dict "value" .hostAliases "context" $) | nindent 8 }}
      {{- else if $.Values.generic.hostAliases }}
      hostAliases: {{- include "helpers.tplvalues.render" (dict "value" $.Values.generic.hostAliases "context" $) | nindent 8 }}
      {{- end }}
      {{- if .affinity }}
      affinity: {{- include "helpers.tplvalues.render" ( dict "value" .affinity "context" $) | nindent 8 }}
      {{- else if $general.affinity }}
      affinity: {{- include "helpers.tplvalues.render" ( dict "value" $general.affinity "context" $) | nindent 8 }}
      {{- else }}
      affinity:
        nodeAffinity: {{- include "helpers.affinities.nodes" (dict "type" $.Values.nodeAffinityPreset.type "key" $.Values.nodeAffinityPreset.key "values" $.Values.nodeAffinityPreset.values) | nindent 10 }}
        podAffinity: {{- include "helpers.affinities.pods" (dict "type" $.Values.podAffinityPreset "context" $) | nindent 10 }}
        podAntiAffinity: {{- include "helpers.affinities.pods" (dict "type" $.Values.podAntiAffinityPreset "context" $) | nindent 10 }}
      {{- end }}
      {{- with .podSecurityContext }}
      securityContext: {{- include "helpers.tplvalues.render" (dict "value" . "context" $) nindent 6 }}
      {{- end }}
      {{- if .dnsPolicy }}
      dnsPolicy: {{ .dnsPolicy }}
      {{- else if $.Values.generic.dnsPolicy }}
      dnsPolicy: {{ $.Values.generic.dnsPolicy }}
      {{- end }}
      {{- with .nodeSelector }}
      nodeSelector: {{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 6 }}
      {{- end }}
      {{- with .tolerations }}
      tolerations: {{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 6 }}
      {{- end }}
      {{ if or $.Values.generic.imagePullSecrets .imagePullSecrets }}
      imagePullSecrets:
        {{- range $sName, $v := $.Values.generic.imagePullSecrets }}
        - name: {{ $sName }}
        {{- end }}
        {{- if .imagePullSecrets }}
        {{- include "helpers.tplvalues.render" ( dict "value" .imagePullSecrets "context" $) | nindent 8 }}
        {{- end }}
      {{- end }}
      {{- with .initContainers}}
      initContainers:
      {{- range . }}
      - name: {{ .name | default $jobName }}
        image: {{ .image | default $.Values.defaultImage }}:{{ .imageTag | default  $.Values.defaultImageTag }}
        imagePullPolicy: {{ .imagePullPolicy | default "IfNotPresent" }}
        {{- with .containerSecurityContext }}
        securityContext: {{- include "helpers.tplvalues.render" ( dict "value" . "context" $) | nindent 8 }}
        {{- end }}
        {{- if and .args (not $job.max_duration) }}
        args: {{- include "helpers.tplvalues.render" ( dict "value" . "context" $) | nindent 14 }}
        {{- end }}
        {{- with .command }}
        {{- if typeIs "string" . }}
        {{- if $job.max_duration }}
        command: ["/bin/bash"]
        args: ["-c", "/usr/bin/timeout --preserve-status {{ $job.max_duration }} {{ . }}; exit_status=$?; if [[ $exit_status -eq 143 ]]; then echo 'Max execution exceeded after {{ $job.max_duration }} seconds (Added by task #91828)!'; fi; exit $exit_status"]
        {{- else }}
        command: {{ printf "[\"%s\"]" (join ("\", \"") (without (splitList " " . ) "" )) }}
        {{- end }}
        {{- else -}}
        command: {{- include "helpers.tplvalues.render" ( dict "value" . "context" $) | nindent 8 }}
        {{- end }}
        {{- end }}
        {{- include "helpers.workloads.envs" (dict "value" . "context" $) | indent 8 }}
        {{- include "helpers.workloads.envsFrom" (dict "value" . "context" $) | indent 8 }}
        {{- with .ports }}
        ports: {{- include "helpers.tplvalues.render" ( dict "value" . "context" $) | nindent 8 }}
        {{- end }}
        {{- with .lifecycle }}
        lifecycle: {{- include "helpers.tplvalues.render" ( dict "value" . "context" $) | nindent 10 }}
        {{- end }}
        {{- with .livenessProbe }}
        livenessProbe: {{- include "helpers.tplvalues.render" ( dict "value" . "context" $) | nindent 10 }}
        {{- end }}
        {{- with .readinessProbe }}
        readinessProbe: {{- include "helpers.tplvalues.render" ( dict "value" . "context" $) | nindent 10 }}
        {{- end }}
        {{- with .resources }}
        resources: {{- include "helpers.tplvalues.render" ( dict "value" . "context" $) | nindent 10 }}
        {{- end }}
        volumeMounts: {{- include "helpers.volumes.renderVolumeMounts" (dict "value" . "general" $general "context" $) | indent 8 }}
      {{- end }}{{- end }}
      {{- $containers := list -}}
      {{- if .containers -}}{{- $containers = .containers -}}{{- else -}}{{- $containers = append list . -}}{{- end }}
      containers:
      {{- range $containers }}
      - name: {{ .name | default $jobName }}
        image: {{ .image | default $.Values.defaultImage }}:{{ .imageTag | default  $.Values.defaultImageTag }}
        imagePullPolicy: {{ .imagePullPolicy | default "IfNotPresent" }}
        {{- with .containerSecurityContext }}
        securityContext: {{- include "helpers.tplvalues.render" ( dict "value" . "context" $) | nindent 8 }}
        {{- end }}
        {{- if and .args (not $job.max_duration) }}
        args: {{- include "helpers.tplvalues.render" ( dict "value" . "context" $) | nindent 8 }}
        {{- end }}
        {{- with .command }}
        {{- if typeIs "string" . }}
        {{- if $job.max_duration }}
        command: ["/bin/bash"]
        args: ["-c", "/usr/bin/timeout --preserve-status {{ $job.max_duration }} {{ . }}; exit_status=$?; if [[ $exit_status -eq 143 ]]; then echo 'Max execution exceeded after {{ $job.max_duration }} seconds (Added by task #91828)!'; fi; exit $exit_status"]
        {{- else }}
        command: {{ printf "[\"%s\"]" (join ("\", \"") (without (splitList " " . ) "" )) }}
        {{- end }}
        {{- else -}}
        command: {{- include "helpers.tplvalues.render" ( dict "value" . "context" $) | nindent 8 }}
        {{- end }}
        {{- end }}
        {{- include "helpers.workloads.envs" (dict "value" . "context" $) | indent 8 }}
        {{- include "helpers.workloads.envsFrom" (dict "value" . "context" $) | indent 8 }}
        {{- with .ports }}
        ports: {{- include "helpers.tplvalues.render" ( dict "value" . "context" $) | nindent 8 }}
        {{- end }}
        {{- with .lifecycle }}
        lifecycle: {{- include "helpers.tplvalues.render" ( dict "value" . "context" $) | nindent 10 }}
        {{- end }}
        {{- with .livenessProbe }}
        livenessProbe: {{- include "helpers.tplvalues.render" ( dict "value" . "context" $) | nindent 10 }}
        {{- end }}
        {{- with .readinessProbe }}
        readinessProbe: {{- include "helpers.tplvalues.render" ( dict "value" . "context" $) | nindent 10 }}
        {{- end }}
        {{- with .resources }}
        resources: {{- include "helpers.tplvalues.render" ( dict "value" . "context" $) | nindent 10 }}
        {{- end }}
        volumeMounts: {{- include "helpers.volumes.renderVolumeMounts" (dict "value" . "general" $general "context" $) | indent 8 }}
      {{- end }}
      volumes: {{- include "helpers.volumes.renderVolume" (dict "value" . "general" $general "context" $) | indent 6}}
      restartPolicy: {{ .restartPolicy | default "Never" }}
{{- end }}
{{- end }}
