{{/*Блок генерит секреты согласно данным из values.yml*/}}
{{- range .Values.secrets }}
---
apiVersion: v1
kind: Secret
type: {{ .type | default  "Opaque" }}
metadata:
  name: {{ include "helpers.app.fullname" (dict "name" .name "context" $) }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{- include "helpers.app.labels" $ | nindent 4 }}
    {{- if .labels }}
    {{- include "helpers.tplvalues.render" (dict "value" .labels "context" $) | nindent 4 }}
    {{- end }}
    {{- if $.Values.global.labels }}
    {{- include "helpers.tplvalues.render" (dict "value" $.Values.global.labels "context" $) | nindent 4 }}
    {{- end }}
data:
  {{- include "helpers.secrets.render" (dict "value" .data) | nindent 2 }}
{{- end }}

{{- if .Values.global.secretEnvs }}
---
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: {{ .Release.Name }}-secrets-env
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "helpers.app.labels" $ | nindent 4 }}
    {{- if .Values.global.labels }}
    {{- include "helpers.tplvalues.render" (dict "value" .Values.global.labels "context" $) | nindent 4 }}
    {{- end }}
data:
  {{- include "helpers.secrets.render" (dict "value" .Values.global.secretEnvs) | nindent 2 }}
{{- end }}

{{- if $.Files.Glob ("extra-files/secret/**") -}}
{{- range $subPath := splitList "$" (include "helpers.secretFiles.subPaths" $)}}
---
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: {{ include "helpers.app.fullname" (dict "name" ($subPath | replace "_" "-") "context" $) }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
  {{- include "helpers.app.labels" $ | nindent 4 }}
  {{- if $.Values.global.labels }}
  {{- include "helpers.tplvalues.render" (dict "value" $.Values.global.labels "context" $) | nindent 4 }}
  {{- end }}
data:
  {{- if eq $subPath "extra-files" }}
  {{ ($.Files.Glob  "extra-files/secret/*").AsSecrets | indent 2 }}
  {{- else }}
  {{ ($.Files.Glob (printf "extra-files/secret/%s/**" $subPath)).AsSecrets | indent 2 }}
  {{- end -}}
{{- end -}}
{{- end -}}