{{/*Блок генерит секреты согласно данным из values.yml*/}}
{{- range .Values.secrets }}
---
apiVersion: v1
kind: Secret
type: {{ .type | default  "Opaque" }}
metadata:
  name: {{ include "helpers.app.fullname" (dict "name" .name "context" $) }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{- include "app.labels" $ | nindent 4 }}
    {{- if .labels }}
    {{- include "helpers.tplvalues.render" (dict "value" .labels "context" $) | nindent 4 }}
    {{- end }}
    {{- if $.Values.global.labels }}
    {{- include "helpers.tplvalues.render" (dict "value" $.Values.global.labels "context" $) | nindent 4 }}
    {{- end }}
data:
  {{- include "helpers.secrets.render" (dict "value" .data) | nindent 2 }}
{{- end }}

{{- if .Values.global.secretEnvs }}
{{/*Блок генерит секрет из значений, переданных через --set*/}}
---
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: {{ .Release.Name }}-secrets-env
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "app.labels" $ | nindent 4 }}
    {{- if .Values.global.labels }}
    {{- include "helpers.tplvalues.render" (dict "value" .Values.global.labels "context" $) | nindent 4 }}
    {{- end }}
data:
  {{- include "helpers.secrets.render" (dict "value" .Values.global.secretEnvs) | nindent 2 }}
{{- end }}
